CREATE TABLE Items (
	itemsID VARCHAR(10) NOT NULL,
	itemName VARCHAR(50),
	itemDescription VARCHAR(255),
	itemPrice NUMBER(7,2),
	itemAvailability VARCHAR(50),
	categoryID VARCHAR(10),
	PRIMARY KEY (itemsID),
	FOREIGN KEY (categoryID) REFERENCES Categories (categoryID),
	CONSTRAINT checkingItemPrice Check(itemPrice >= 0),
	CONSTRAiNT chk_itemsid CHECK (itemsID LIKE 'I%')
);

INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I001', 'Premium Chicken Chop', 'Tender and juicy chicken chop seasoned with our special blend of herbs and spices, grilled to perfection.', 24.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I002', 'Grilled Chicken Chop', 'A healthier alternative to our premium chicken chop, grilled to perfection without compromising on flavor.', 26.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I003', 'Grilled Pork Chop', 'Succulent pork chop marinated with a savory mix of herbs and spices, grilled to perfection.', 30.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I004', 'Golden Fish Fillet', 'Crispy and flavorful fish fillet coated with our special batter, deep-fried to a golden brown.', 31.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I005', 'Norwegian Salmon With Lemon Butter Sauce', 'Fresh Norwegian salmon served with a zesty lemon butter sauce, a delectable choice for seafood lovers.', 46.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I006', 'Kerabu Chicken Chop', 'An explosion of flavors! Our traditional Malaysian-style chicken chop topped with spicy and tangy kerabu salad.', 29.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I007', 'Kerabu Fish Fillet', 'A fusion of tastes! Our golden fish fillet topped with refreshing and zesty kerabu salad.', 34.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I008', 'Forest Curry Chicken Chop', 'A delightful blend of Malaysian and Thai influences, our chicken chop is smothered in aromatic forest curry sauce.', 26.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I009', 'Kerabu Salmon', 'Fresh Norwegian salmon paired with spicy and tangy kerabu salad, a mouthwatering combination.', 46.00, 'Available', 'CA001');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I010', 'AI Fungi', 'A vegetarian delight! Pasta tossed in a creamy mushroom sauce with a medley of fresh mushrooms.', 23.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I011', 'Chicken Bolognese', 'Hearty and satisfying! Spaghetti served with a rich and savory chicken bolognese sauce.', 22.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I012', 'Classic Carbonara', 'Indulge in the classic Italian favorite! Spaghetti tossed in a creamy carbonara sauce with bacon and parmesan cheese.', 29.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I013', 'Seafood Aglio Olio', 'Simple yet flavorful! Spaghetti infused with garlic, chili flakes, and olive oil, topped with a medley of fresh seafood.', 31.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I014', 'Grilled Salmon Aglio Olio', 'Healthy and delicious! Grilled salmon served on a bed of aglio olio pasta, a perfect combination.', 34.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I015', 'Spicy And Creamy Seafood Pasta', 'An explosion of flavors! Creamy pasta with a spicy kick, loaded with a variety of delectable seafood.', 32.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I016', 'Seafood Marinara', 'A seafood lovers dream! Pasta served with a rich marinara sauce, brimming with the goodness of fresh seafood.', 31.00, 'Available', 'CA002');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I017', 'Peanut Sauce Pork Burger', 'Juicy pork patty topped with a savory peanut sauce, a unique twist to a classic burger.', 29.00, 'Available', 'CA003');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I018', 'Golden Fish Burger', 'A seafood delight! Crispy fish fillet served on a soft burger bun with fresh vegetables and special sauce.', 24.00, 'Available', 'CA003');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I019', 'Wagyu Beef Burger', 'Indulge in the ultimate burger experience! Premium wagyu beef patty topped with gourmet ingredients.', 39.00, 'Available', 'CA003');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I020', 'Hot And Spicy Chicken Burger', 'For spice enthusiasts! Fiery hot chicken patty served on a toasted bun with cooling accompaniments.', 31.00, 'Available', 'CA003');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I021', 'Signature Cheese Pizza', 'A timeless favorite! Our classic cheese pizza with a thin and crispy crust.', 30.00, 'Available', 'CA004');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I022', 'Hawaiian Chicken Pizza', 'Tropical flavors in every bite! Savory chicken, juicy pineapple, and melted cheese on a pizza crust.', 23.00, 'Available', 'CA004');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I023', 'Mediterranean Seafood Pizza', 'A taste of the Mediterranean! A seafood pizza loaded with fresh seafood and Mediterranean herbs.', 43.00, 'Available', 'CA004');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I024', 'Garlic Bread (A la carte)', 'Buttery and garlicky, our garlic bread makes for a delightful appetizer or side.', 10.00, 'Available', 'CA005');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I025', 'Mushroom Soup (A la carte)', 'A comforting bowl of creamy mushroom soup, made with a blend of fresh mushrooms.', 11.00, 'Available', 'CA005');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I026', 'Mashed Potato (A la carte)', 'Smooth and buttery mashed potatoes, the perfect accompaniment to any main course.', 11.00, 'Available', 'CA005');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I027', 'French Fries', 'Golden, crispy, and perfectly salted, our classic French fries are the perfect side for any meal.', 14.00, 'Available', 'CA006');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I028', 'Wedges', 'Crispy and seasoned potato wedges, a delightful alternative to traditional French fries.', 16.00, 'Available', 'CA006');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I029', 'Chicken Wings', 'Juicy and flavorful chicken wings, served with your choice of dipping sauce.', 24.00, 'Available', 'CA006');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I030', 'Jumbo Hotdog', 'A classic favorite! A jumbo-sized hotdog served in a soft bun with a variety of toppings.', 16.00, 'Available', 'CA006');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I031', 'Popcorn Chicken', 'Addictively delicious! Bite-sized pieces of fried chicken, perfect for snacking.', 22.00, 'Available', 'CA006');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I032', 'Apple Juice', '100% pure apple juice, refreshing and natural.', 12.00, 'Available', 'CA007');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I033', 'Orange Juice', 'Freshly squeezed orange juice, bursting with vitamin C.', 12.00, 'Available', 'CA007');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I034', 'Watermelon Juice', 'Cool and refreshing watermelon juice, perfect for quenching your thirst.', 12.00, 'Available', 'CA007');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I035', '100 Plus', 'The ultimate thirst quencher! An isotonic drink to rehydrate and re-energize.', 8.00, 'Available', 'CA008');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I036', 'Coke', 'Classic Coca-Cola, a timeless fizzy beverage.', 8.00, 'Available', 'CA008');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I037', 'Sprite', 'Zesty and refreshing Sprite, a perfect accompaniment to any meal.', 8.00, 'Available', 'CA008');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I038', 'Oreo Ice Blended', 'A delightful icy treat! Creamy Oreo ice blended to perfection.', 17.00, 'Available', 'CA009');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I039', 'Oreo Milkshake', 'Indulge in the classic Oreo milkshake, rich and velvety.', 18.00, 'Available', 'CA009');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I040', 'Chocolate Ice Blended', 'A chocolate lovers delight! A rich and smooth chocolate ice blended beverage.', 18.00, 'Available', 'CA009');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I041', 'Chocolate Milkshake', 'Creamy and chocolaty! A classic chocolate milkshake that never disappoints.', 19.00, 'Available', 'CA009');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I042', 'Matcha Ice Blended', 'For matcha enthusiasts! A refreshing ice blended drink with the goodness of matcha.', 19.00, 'Available', 'CA009');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I043', 'Classic Mojito', 'A classic cocktail made with fresh mint leaves, lime, sugar, and sparkling water.', 25.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I044', 'Royal Martini', 'Elevate your evening with our royal martini, a sophisticated and timeless cocktail.', 25.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I045', 'Raspberry Mojito', 'A fruity twist on the classic mojito, with the addition of fresh raspberries.', 25.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I046', 'Bourbon Flip', 'For bourbon enthusiasts! A smooth and indulgent bourbon-based cocktail.', 25.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I047', 'Manhattan', 'A timeless classic! Rye whiskey, vermouth, and bitters come together in this iconic cocktail.', 25.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I048', 'Tiger', 'A crisp and refreshing lager beer, perfect for enjoying with friends.', 13.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I049', 'Heineken', 'A premium lager beer with a balanced and smooth taste.', 15.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I050', 'Guinness', 'A rich and velvety stout beer with notes of coffee and chocolate.', 15.00, 'Available', 'CA010');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I051', 'Vanilla Ice Cream', 'Indulge in the timeless allure of our creamy vanilla ice cream.', 5.00, 'Available', 'CA011');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I052', 'Chocolate Ice Cream', 'Dive into the indulgent charm of our smooth chocolate ice cream.', 5.00, 'Available', 'CA011');
INSERT INTO Items (itemsID, itemName, itemDescription, itemPrice, itemAvailability, categoryID) VALUES ('I053', 'Cheese Cake', 'Velvety cheesecake perfection with a buttery crust.', 8.00, 'Available', 'CA011');
